### ISSUE TITLE
Where to access "shared folder"

### ISSUE THREAD

**Issue by ChengLongHang** [oi-analytics/oi-risk-vis#10]
Under the subheading "Prepare Data" in the README document, it mentions downloading _"boundaries, network and flood_data usage results from the shared folder."_ . Would like to know how to access the data. Thanks!

**Comment by tomalrussell** [comment]
The shared folder is not publicly available.

However, all project outputs were archived in the World Bank Data Catalog:
- https://datacatalog.worldbank.org/search/dataset/0042426/South-East-Asia-transport-network
- https://datacatalog.worldbank.org/search/dataset/0042425/South-East-Asia-electric-grid
- https://datacatalog.worldbank.org/search/dataset/0042422/South-East-Asia-strong-wind-hazard--tropical-cyclone-
- https://datacatalog.worldbank.org/search/dataset/0050606/South-East-Asia-strong-wind-risk--tropical-cyclone-
- https://datacatalog.worldbank.org/search/dataset/0042424/South-East-Asia-coastal-flood-hazard
- https://datacatalog.worldbank.org/search/dataset/0050607/South-East-Asia-coastal-flood-risk
- https://datacatalog.worldbank.org/search/dataset/0042423/South-East-Asia-river-flood-hazard
- https://datacatalog.worldbank.org/search/dataset/0050609/South-East-Asia-river-flood-risk

There is no guarantee that these have been maintained in compatible formats or filename/directory layouts. This project ended three years ago and is not actively supported.

The project report is online at https://thedocs.worldbank.org/en/doc/1019bd2696cf0660968910763351f601-0240012021/analytics-for-financial-risk-management-of-critical-infrastructure-in-southeast-asia-scoping-feasibility-study ([attached](https://github.com/user-attachments/files/16195803/Analytics-for-Financial-Risk-Management-of-Critical-Infrastructure-in-Southeast-Asia.pdf))
