### ISSUE TITLE
Clarification on server setup/data files

### ISSUE THREAD

**Issue by ConnectedSystems** [oi-analytics/oi-risk-vis#7]
Hello

I'm helping GFDRR on the project backup of data and code. I just forked the seasia and oi-risk-vis repos on to the GFDRR account and I wanted to make sure we understand all the necessary elements to run the tool again in the future. 

I tried to deploy it locally, but I'm stuck at the server deployment stage as it seems I do not have the expected data files. 

I had a look at the [seasia repo](https://github.com/GFDRR/seasia) and it seems to process/convert data from mid/mif (the data format we got from Gordon) to geopackage, but the viz tool appears to expect shapefiles instead?

Wondering if you could help us with some clarification on the data workflow, and whether I am missing something.

Thank you

**Comment by tomalrussell** [comment]
Hi @ConnectedSystems 

There are two elements to the data:

CSV files that used to create the regional line charts. 
- created from the "summary" output files using this [notebook](https://github.com/GFDRR/seasia/blob/main/postprocess/admin_summaries_to_charts.ipynb) in the seasia repo.

MBTiles files containing Mapbox Vector Tiles to visualise networks, hazards and risk. 
- ad-hoc scripts convert from the MID/MIF files to json, picking out only the attributes needed for visualisation.
- some of this is recorded in shell scripts in [scripts](https://github.com/GFDRR/oi-risk-vis/tree/master/scripts). I'm afraid that `files_to_json_for_vis.py` is out of date and should be deleted to save on confusion, apologies for that.
- finally `tippecanoe` converts json to mbtiles - commands in [Makefile](https://github.com/GFDRR/oi-risk-vis/blob/master/Makefile)

I'll upload both processed CSVs and MBTiles to the blob storage under `seasia/OIA_SEA_Data/5_tool` so you have a full set for reference (should complete in an hour or so).

Let me know if you have any more questions

**Comment by ConnectedSystems** [comment]
Thanks @tomalrussell , I can get the tool up and running with the provided data set. Very much appreciated!
